# Generated by Django 2.1.15 on 2020-02-20 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmendmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amendment_type', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChildContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_vendor_number', models.PositiveIntegerField(default=None, null=True)),
                ('child_vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('child_contr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('child_PGrp', models.CharField(blank=True, max_length=50, null=True)),
                ('child_POrg', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form2_contr_num', models.PositiveIntegerField(default=None, null=True)),
                ('form2_contr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('form2_vendor_number', models.PositiveIntegerField(default=None, null=True)),
                ('form2_vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('form2_validity_start', models.DateTimeField(null=True)),
                ('form2_validity_end', models.DateTimeField(null=True)),
                ('form2_POrg', models.CharField(blank=True, max_length=100, null=True)),
                ('form2_PGrp', models.CharField(blank=True, max_length=100, null=True)),
                ('form2_target_value', models.PositiveIntegerField(default=None, null=True)),
                ('form2_currency', models.CharField(blank=True, max_length=100, null=True)),
                ('form2_payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('form2_incoterm', models.CharField(blank=True, max_length=100, null=True)),
                ('form2_reasons_for_outside', models.CharField(blank=True, max_length=100, null=True)),
                ('form2_child_or_parent', models.CharField(blank=True, max_length=20, null=True)),
                ('form2_owner_email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_vendor_number', models.PositiveIntegerField(default=None, null=True)),
                ('parent_vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_contr_name', models.CharField(blank=True, max_length=40, null=True)),
                ('parent_PGrp', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_POrg', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_contr_number', models.BigIntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('contract_type', models.CharField(max_length=100, null=True)),
                ('request_type', models.CharField(max_length=100, null=True)),
                ('paper_contr_type', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('sub_category', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='parentcontract',
            name='parent_contract_setup_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='csa_app.Setup'),
        ),
        migrations.AddField(
            model_name='form2',
            name='form2_setup_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='csa_app.Setup'),
        ),
        migrations.AddField(
            model_name='childcontract',
            name='child_contract_setup_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='csa_app.Setup'),
        ),
        migrations.AddField(
            model_name='amendmenttype',
            name='setup_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='csa_app.Setup'),
        ),
    ]
