# Generated by Django 2.1.15 on 2020-02-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form2',
            name='form2_contr_num',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
