# Generated by Django 2.2.5 on 2020-01-27 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csa_app', '0002_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcontract',
            name='child_parent_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='csa_app.Setup'),
        ),
    ]
