# Generated by Django 2.2.5 on 2020-01-27 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csa_app', '0003_auto_20200126_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childcontract',
            old_name='child_parent_ref',
            new_name='child_contract_setup_ref',
        ),
    ]
