# Generated by Django 2.1.15 on 2020-02-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csa_app', '0003_form5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form5',
            name='form5_1',
            field=models.BooleanField(default=False),
        ),
    ]
