# Generated by Django 2.1.15 on 2020-02-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csa_app', '0004_auto_20200227_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form5',
            name='form5_10',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form5',
            name='form5_11',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form5',
            name='form5_12',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form5',
            name='form5_13',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form5',
            name='form5_14',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form5',
            name='form5_15',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form5',
            name='form5_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form5',
            name='form5_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form5',
            name='form5_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form5',
            name='form5_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form5',
            name='form5_6',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form5',
            name='form5_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form5',
            name='form5_8',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form5',
            name='form5_9',
            field=models.BooleanField(default=False),
        ),
    ]
