# Generated by Django 2.2.5 on 2020-01-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csa_app', '0005_auto_20200130_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='form2',
            name='form2_child_or_parent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
