# Generated by Django 3.0.3 on 2020-03-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csa_app', '0006_auto_20200228_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='form2',
            name='form2_plant_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
