# Generated by Django 2.2.5 on 2020-02-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csa_app', '0006_form2_form2_child_or_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='form2',
            name='form2_incoterm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form2',
            name='form2_PGrp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form2',
            name='form2_POrg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form2',
            name='form2_currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
