# Generated by Django 2.2.5 on 2020-02-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csa_app', '0007_auto_20200202_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='form2',
            name='form2_owner_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
