PGRps_list = [(None,'Select PGrp'),('Oilsands 001', 'Oilsands 001'),('Oilsands 003', 'Oilsands 003'),('Oilsands 004', 'Oilsands 004'),
 ('Oilsands 005', 'Oilsands 005'),('Oilsands 006', 'Oilsands 006'),('Oilsands 007', 'Oilsands 007'),('Oilsands 008', 'Oilsands 008'),('Oilsands 009', 'Oilsands 009'),
 ('Oilsands 010', 'Oilsands 010'),('Oilsands 011', 'Oilsands 011'),('Oilsands 014', 'Oilsands 014'),('Oilsands 015', 'Oilsands 015'),('Oilsands 017', 'Oilsands 017'),
 ('Oilsands 018', 'Oilsands 018'),('Oilsands 019', 'Oilsands 019'),('Oilsands 021', 'Oilsands 021'),('Oilsands 023', 'Oilsands 023'),('Oilsands 026', 'Oilsands 026'),
 ('Oilsands 028', 'Oilsands 028'),('Oilsands 031', 'Oilsands 031'),('Oilsands 032', 'Oilsands 032'),('Oilsands 033', 'Oilsands 033'),('Oilsands 034', 'Oilsands 034'),
 ('Oilsands 035', 'Oilsands 035'),('Oilsands 036', 'Oilsands 036'),('Oilsands 037', 'Oilsands 037'),('Oilsands 038', 'Oilsands 038'),('Oilsands 041', 'Oilsands 041'),
 ('Oilsands 042', 'Oilsands 042'),('Oilsands 043', 'Oilsands 043'),('Oilsands 045', 'Oilsands 045'),('Oilsands 046', 'Oilsands 046'),('Oilsands 047', 'Oilsands 047'),
 ('Oilsands 051', 'Oilsands 051'),('Oilsands 052', 'Oilsands 052'),('Oilsands 055', 'Oilsands 055'),('Oilsands 056', 'Oilsands 056'),('Oilsands 057', 'Oilsands 057'),
 ('Oilsands 058', 'Oilsands 058'),('Oilsands 060', 'Oilsands 060'),('Oilsands 062', 'Oilsands 062'),('Oilsands 063', 'Oilsands 063'),('Oilsands 064', 'Oilsands 064'),
 ('Oilsands 065', 'Oilsands 065'),('Oilsands 066', 'Oilsands 066'),('Oilsands 067', 'Oilsands 067'),('Oilsands 068', 'Oilsands 068'),('Oilsands 069', 'Oilsands 069'),
 ('Oilsands 070', 'Oilsands 070'),('Oilsands 071', 'Oilsands 071'),('Oilsands 072', 'Oilsands 072'),('Oilsands 073', 'Oilsands 073'),('Oilsands 074', 'Oilsands 074'),
 ('Oilsands 075', 'Oilsands 075'),('Oilsands 076', 'Oilsands 076'),('Oilsands 078', 'Oilsands 078'),('Oilsands 084', 'Oilsands 084'),('Oilsands 085', 'Oilsands 085'),
 ('Oilsands 087', 'Oilsands 087'),('Oilsands 088', 'Oilsands 088'),('Oilsands 089', 'Oilsands 089'),('Oilsands 091', 'Oilsands 091'),('Oilsands 094', 'Oilsands 094'),
 ('Oilsands 095', 'Oilsands 095'),('Oilsands 097', 'Oilsands 097'),('Oilsands 098', 'Oilsands 098'),('Oilsands 100', 'Oilsands 100'),('Oilsands 101', 'Oilsands 101'),
 ('Oilsands 103', 'Oilsands 103'),('Oilsands 104', 'Oilsands 104'),('Oilsands 117', 'Oilsands 117'),('Oilsands 119', 'Oilsands 119'),('Oilsands 120', 'Oilsands 120'),
 ('Upgrading/E&U - 206', 'Upgrading/E&U - 206'),('TA/SWS - 258', 'TA/SWS - 258'),('Mining - 272', 'Mining - 272'),('Mining - 276', 'Mining - 276'),
 ('Upstream - 302', 'Upstream - 302'),('SEOI - 1750 - A01', 'SEOI - 1750 - A01'),('Inventory - B01', 'Inventory - B01'),('Inventory - B14', 'Inventory - B14'),
 ('General Default - C01', 'General Default - C01'),('Corporate - C10', 'Corporate - C10'),('Corporate - C11', 'Corporate - C11'),('Corporate - C12', 'Corporate - C12'),
 ('Corporate - C13', 'Corporate - C13'),('Corporate - C14', 'Corporate - C14'),('Corporate - C15', 'Corporate - C15'),('Corporate - C16', 'Corporate - C16'),
 ('Corporate - C17', 'Corporate - C17'),('E&P Corporate Proc - CEP', 'E&P Corporate Proc - CEP'),('Corporate - C11', 'Corporate - C11'),
 ('Commerce City - 14', 'Commerce City - 14'),('Sarnia - D24', 'Sarnia - D24'),('Lubricants - D33', 'Lubricants - D33'),('Lubricants - D34', 'Lubricants - D34'),
 ('Lubricants - D37', 'Lubricants - D37'),('Edmonton - D40', 'Edmonton - D40'),('Edmonton - D42', 'Edmonton - D42'),('Edmonton - D46', 'Edmonton - D46'),
 ('Rack Forward - D50', 'Rack Forward - D50'),('Rack Forward - D51', 'Rack Forward - D51'),('Rack Forward - D52', 'Rack Forward - D52'),('Rack Forward - D53', 'Rack Forward - D53'),
 ('Rack Forward - D54', 'Rack Forward - D54'),('Den Sust Capital - DE1', 'Den Sust Capital - DE1'),
 ('Suncor Denver - DE3', 'Suncor Denver - DE3'),('Denver Turnarounds - DE4', 'Denver Turnarounds - DE4'),('Suncor Denver - DEN', 'Suncor Denver - DEN'),
 ('FB Jacobs - E01', 'FB Jacobs - E01'),('M&E Site - E02', 'M&E Site - E02'),('MP Site Serv - E04', 'MP Site Serv - E04'),('FB Sust Proj - E05', 'FB Sust Proj - E05'),
 ('VU Common - 1730 - E15', 'VU Common - 1730 - E15'),('Sustaining Project - E56', 'Sustaining Project - E56'),('VU U&O - EB2', 'VU U&O - EB2'),('MP Fort Hills - EFH', 'MP Fort Hills - EFH'),
 ('Fort Hills - F01', 'Fort Hills - F01'),('Fort Hills - F13', 'Fort Hills - F13'),('Fort Hills - F15', 'Fort Hills - F15'),('Fort Hills - F26', 'Fort Hills - F26'),
 ('Fort Hills - F29', 'Fort Hills - F29'),('Corp IT - I01', 'Corp IT - I01'),('Corp IT - I02', 'Corp IT - I02'),('Corp IT - I03', 'Corp IT - I03'),
 ('Corp IT - I04', 'Corp IT - I04'),('Corp IT - I05', 'Corp IT - I05'),('I&O UK 01 - IO1', 'I&O UK 01 - IO1'),('I&O Norway 01 - IO2', 'I&O Norway 01 - IO2'),
 ('I&O Terra Nova - IO3', 'I&O Terra Nova - IO3'),('I&O East Coast 01 - IO4', 'I&O East Coast 01 - IO4'),('I&O UK 08 - IO8', 'I&O UK 08 - IO8'),('IO NORWAY IT 03 - IO9', 'IO NORWAY IT 03 - IO9'),
 ('N.Oper In Situ - IS1', 'N.Oper In Situ - IS1'),('IT Purchasing - ITB', 'IT Purchasing - ITB'),('LPX Schedule - L01', 'LPX Schedule - L01'),('LPX Additives - L02', 'LPX Additives - L02'),
 ('Lubes SCM - L03', 'Lubes SCM - L03'),('Lubeplex Manufactu - L06', 'Lubeplex Manufactu - L06'),('Lubes Projects - L07', 'Lubes Projects - L07'),('Rack Back Material - L08', 'Rack Back Material - L08'),
 ('Rack Back Services - L09', 'Rack Back Services - L09'),('General Major Projects - M99', 'General Major Projects - M99'),('Adelaide MA1', 'Adelaide MA1'),('VU Upside T&P - R3 MU1', 'VU Upside T&P - R3 MU1'),
 ('NG WES - NG1', 'NG WES - NG1'),("NG Fac's & P/l's - NG2", "NG Fac's & P/l's - NG2"),('EDMR Materials - R01', 'EDMR Materials - R01'),('EDMR (Turn Around) - R02', 'EDMR (Turn Around) - R02'),
 ('EDMR Capital (E&C) - R07', 'EDMR Capital (E&C) - R07'),('EDMR Util and P&S - R08', 'EDMR Util and P&S - R08'),('Burrard-Mat & Srvc - R15', 'Burrard-Mat & Srvc - R15'),
 ('MTLR - Sect. 1 Ent - R31', 'MTLR - Sect. 1 Ent - R31'),('MTLR - Sect. 2 Ent - R32', 'MTLR - Sect. 2 Ent - R32'),('MTLR - Sect. 3 Ent - R33', 'MTLR - Sect. 3 Ent - R33'),
 ('MTLR -Sect. 4 Ent - R34', 'MTLR -Sect. 4 Ent - R34'),('MTLR - Ing/Project - R35', 'MTLR - Ing/Project - R35'),('MTLR - Codes Art. - R37', 'MTLR - Codes Art. - R37'),
 ('RFWD - Materials - R55', 'RFWD - Materials - R55'),('RFWD - Services - R56', 'RFWD - Services - R56'),('RFWD - Projects - R57', 'RFWD - Projects - R57'),
 ('Rack Forward - R58', 'Rack Forward - R58'),('IS Resources - R99', 'IS Resources - R99'),('RE Suncor SEPI - RE7', 'RE Suncor SEPI - RE7'),('Canadian Refinery1 - SA1', 'Canadian Refinery1 - SA1'),
 ('Canadian Refinery2 - SA2', 'Canadian Refinery2 - SA2'),('Canadian Refinery4 - SA4', 'Canadian Refinery4 - SA4'),('Canadian Refinery5 - SA5', 'Canadian Refinery5 - SA5'),
 ('SE Developments - SED', 'SE Developments - SED'),('SEMI Purchasing - SEM', 'SEMI Purchasing - SEM'),('Suncor SESI - SES', 'Suncor SESI - SES'),('EDMR CDN Pipelines - SP1', 'EDMR CDN Pipelines - SP1'),
 ('SE (USA) Pipeline - USP', 'SE (USA) Pipeline - USP')
 ]

POrgs_list = [
        (None,'Select POrg'), ('Fort Hills POrg 5', 'Fort Hills POrg 5'), ('United Kingdom POrg 10','United Kingdom POrg 10'),
        ('Non Operating POrg 11','Non Operating POrg 11'),('Petro Canada Lubricants POrg 12','Petro Canada Lubricants POrg 12'),
        ('Norge POrg 15','Norge POrg 15'),('Oil Sands POrg 1000','Oil Sands POrg 1000'),('SECPLP POrg 1030','SECPLP POrg 1030'),
        ('Forty Mile Granlea Wind LP','Forty Mile Granlea Wind LP'),('East Coast POrg 1505','East Coast POrg 1505'),('Terra Nova POrg 1525','Terra Nova POrg 1525'),
        ('Voyageur POrg 1730','Voyageur POrg 1730'),('SEOI POrg 1750','SEOI POrg 1750'),('Oilsands PO (TLP) 1765','Oilsands PO (TLP) 1765'),
        ('NatGas POrg 2000','NatGas POrg 2000'),('Corporate POrg 3000','Corporate POrg 3000'),('SEDI POrg 3010','SEDI POrg 3010'),
        ('SEPP POrg 4000','SEPP POrg 4000'),('RE Suncor SEPI POrg 4001','RE Suncor SEPI POrg 4001'),('SESI POrg 5000','SESI POrg 5000'),
        ('SEMI POrg 6000','SEMI POrg 6000'),('Denver POrg 7000','Denver POrg 7000'),('SE SEUSAPLCO POrg 7600','SE SEUSAPLCO POrg 7600'),
        ('Ren Energy Magrath POrg 8000','Ren Energy Magrath POrg 8000'),('Adelaide PO 8015','Adelaide PO 8015')
]

currency_list = [
(None,'Select Currency'),
('ADP Andoran peseta', 'ADP Andoran peseta'),
 ('AED United Arab Emirates Dirham', 'AED United Arab Emirates Dirham'),
 ('AFA Afghani', 'AFA Afghani'),
 ('ALL Albanian Lek', 'ALL Albanian Lek'),
 ('AMD Armenian Dram', 'AMD Armenian Dram'),
 ('ANG West Indian Guilder', 'ANG West Indian Guilder'),
 ('AON Angolan New Kwanza', 'AON Angolan New Kwanza'),
 ('AOR Angolan Kwanza Reajustado', 'AOR Angolan Kwanza Reajustado'),
 ('ARS Argentine Peso', 'ARS Argentine Peso'),
 ('ATS Austrian Schilling', 'ATS Austrian Schilling'),
 ('AUD Australian Dollar', 'AUD Australian Dollar'),
 ('AWG Aruban Guilder', 'AWG Aruban Guilder'),
 ('AZM Azerbaijan Manat', 'AZM Azerbaijan Manat'),
 ('BAM Bosnia and Herzegovina Convertible Mark',
  'BAM Bosnia and Herzegovina Convertible Mark'),
 ('BBD Barbados Dollar', 'BBD Barbados Dollar'),
 ('BDT Bangladesh Taka', 'BDT Bangladesh Taka'),
 ('BEF Belgian Franc', 'BEF Belgian Franc'),
 ('BGN Bulgarian Lev', 'BGN Bulgarian Lev'),
 ('BHD Bahrain Dinar', 'BHD Bahrain Dinar'),
 ('BIF Burundi Franc', 'BIF Burundi Franc'),
 ('BMD Bermudan Dollar', 'BMD Bermudan Dollar'),
 ('BND Brunei Dollar', 'BND Brunei Dollar'),
 ('BOB Boliviano', 'BOB Boliviano'),
 ('BRL Brazilian Real', 'BRL Brazilian Real'),
 ('BSD Bahaman Dollar', 'BSD Bahaman Dollar'),
 ('BTN Bhutan Ngultrum', 'BTN Bhutan Ngultrum'),
 ('BWP Botswana Pula', 'BWP Botswana Pula'),
 ('BYB Belorussian Ruble', 'BYB Belorussian Ruble'),
 ('BZD Belize Dollar', 'BZD Belize Dollar'),
 ('CAD Canadian Dollar', 'CAD Canadian Dollar'),
 ('CD6 Canadian Dollar for six decimal places',
  'CD6 Canadian Dollar for six decimal places'),
 ('CDC Canadian Dollar Cents', 'CDC Canadian Dollar Cents'),
 ('CFP French Franc (Pacific Islands)', 'CFP French Franc (Pacific Islands)'),
 ('CHF Swiss Franc', 'CHF Swiss Franc'),
 ('CLP Chilean Peso', 'CLP Chilean Peso'),
 ('CNY Chinese Yuan Renminbi', 'CNY Chinese Yuan Renminbi'),
 ('COP Colombian Peso', 'COP Colombian Peso'),
 ('CRC Costa Rica Colon', 'CRC Costa Rica Colon'),
 ('CUP Cuban Peso', 'CUP Cuban Peso'),
 ('CVE Cape Verde Escudo', 'CVE Cape Verde Escudo'),
 ('CYP Cyprus Pound', 'CYP Cyprus Pound'),
 ('CZK Czech Krona', 'CZK Czech Krona'),
 ('DEM German Mark', 'DEM German Mark'),
 ('DJF Djibouti Franc', 'DJF Djibouti Franc'),
 ('DKK Danish Krone', 'DKK Danish Krone'),
 ('DOP Dominican Peso', 'DOP Dominican Peso'),
 ('DZD Algerian Dinar', 'DZD Algerian Dinar'),
 ('ECS Ecuadorian Sucre', 'ECS Ecuadorian Sucre'),
 ('EEK Estonian Krone', 'EEK Estonian Krone'),
 ('EGP Egyptian Pound', 'EGP Egyptian Pound'),
 ('ERN Eritrean Nafka', 'ERN Eritrean Nafka'),
 ('ESP Spanish Peseta', 'ESP Spanish Peseta'),
 ('ETB Ethiopian Birr', 'ETB Ethiopian Birr'),
 ('EUR European Euro', 'EUR European Euro'),
 ('FIM Finnish markka', 'FIM Finnish markka'),
 ('FJD Fiji Dollar', 'FJD Fiji Dollar'),
 ('FKP Falkland Pound', 'FKP Falkland Pound'),
 ('FRF French Franc', 'FRF French Franc'),
 ('GBP British Pound', 'GBP British Pound'),
 ('GEL Georgian Lari', 'GEL Georgian Lari'),
 ('GHC Ghanian Cedi', 'GHC Ghanian Cedi'),
 ('GIP Gibraltar Pound', 'GIP Gibraltar Pound'),
 ('GMD Gambian Dalasi', 'GMD Gambian Dalasi'),
 ('GNF Guinean Franc', 'GNF Guinean Franc'),
 ('GRD Greek Drachma', 'GRD Greek Drachma'),
 ('GTQ Guatemalan Quetzal', 'GTQ Guatemalan Quetzal'),
 ('GWP Guinea Peso', 'GWP Guinea Peso'),
 ('GYD Guyana Dollar', 'GYD Guyana Dollar'),
 ('HKD Hong Kong Dollar', 'HKD Hong Kong Dollar'),
 ('HNL Honduran Lempira', 'HNL Honduran Lempira'),
 ('HRK Croatian Kuna', 'HRK Croatian Kuna'),
 ('HTG Haitian Gourde', 'HTG Haitian Gourde'),
 ('HUF Hungarian Forint', 'HUF Hungarian Forint'),
 ('IDR Indonesian Rupiah', 'IDR Indonesian Rupiah'),
 ('IEP Irish Punt', 'IEP Irish Punt'),
 ('ILS Israeli Scheckel', 'ILS Israeli Scheckel'),
 ('INR Indian Rupee', 'INR Indian Rupee'),
 ('IQD Iraqui Dinar', 'IQD Iraqui Dinar'),
 ('IRR Iranian Rial', 'IRR Iranian Rial'),
 ('ISK Iceland Krona', 'ISK Iceland Krona'),
 ('ITL Italian Lira', 'ITL Italian Lira'),
 ('JMD Jamaican Dollar', 'JMD Jamaican Dollar'),
 ('JOD Jordanian Dinar', 'JOD Jordanian Dinar'),
 ('JPY Japanese Yen', 'JPY Japanese Yen'),
 ('KES Kenyan Shilling', 'KES Kenyan Shilling'),
 ('KGS Kyrgyzstan Som', 'KGS Kyrgyzstan Som'),
 ('KHR Cambodian Riel', 'KHR Cambodian Riel'),
 ('KMF Comoros Franc', 'KMF Comoros Franc'),
 ('KPW North Korean Won', 'KPW North Korean Won'),
 ('KRW South Korean Won', 'KRW South Korean Won'),
 ('KWD Kuwaiti Dinar', 'KWD Kuwaiti Dinar'),
 ('KYD Cayman Dollar', 'KYD Cayman Dollar'),
 ('KZT Kazakstanian Tenge', 'KZT Kazakstanian Tenge'),
 ('LAK Laotian Kip', 'LAK Laotian Kip'),
 ('LBP Lebanese Pound', 'LBP Lebanese Pound'),
 ('LKR Sri Lankan Rupee', 'LKR Sri Lankan Rupee'),
 ('LRD Liberian Dollar', 'LRD Liberian Dollar'),
 ('LSL Lesotho Loti', 'LSL Lesotho Loti'),
 ('LTL Lithuanian Lita', 'LTL Lithuanian Lita'),
 ('LUF Luxembourg Franc', 'LUF Luxembourg Franc'),
 ('LVL Latvian Lat', 'LVL Latvian Lat'),
 ('LYD Libyan Dinar', 'LYD Libyan Dinar'),
 ('MAD Moroccan Dirham', 'MAD Moroccan Dirham'),
 ('MDL Moldavian Leu', 'MDL Moldavian Leu'),
 ('MGF Madagascan Franc', 'MGF Madagascan Franc'),
 ('MKD Macedonian Denar', 'MKD Macedonian Denar'),
 ('MMK Myanmar Kyat', 'MMK Myanmar Kyat'),
 ('MNT Mongolian Tugrik', 'MNT Mongolian Tugrik'),
 ('MOP Macao Pataca', 'MOP Macao Pataca'),
 ('MRO Mauritanian Ouguiya', 'MRO Mauritanian Ouguiya'),
 ('MTL Maltese Lira', 'MTL Maltese Lira'),
 ('MUR Mauritian Rupee', 'MUR Mauritian Rupee'),
 ('MVR Maldive Rufiyaa', 'MVR Maldive Rufiyaa'),
 ('MWK Malawi Kwacha', 'MWK Malawi Kwacha'),
 ('MXN Mexican Pesos', 'MXN Mexican Pesos'),
 ('MYR Malaysian Ringgit', 'MYR Malaysian Ringgit'),
 ('MZM Mozambique Metical', 'MZM Mozambique Metical'),
 ('NAD Namibian Dollar', 'NAD Namibian Dollar'),
 ('NGN Nigerian Naira', 'NGN Nigerian Naira'),
 ('NIO Nicaraguan Cordoba Oro', 'NIO Nicaraguan Cordoba Oro'),
 ('NLG Dutch Guilder', 'NLG Dutch Guilder'),
 ('NOK Norwegian Krone', 'NOK Norwegian Krone'),
 ('NPR Nepalese Rupee', 'NPR Nepalese Rupee'),
 ('NZD New Zealand Dollars', 'NZD New Zealand Dollars'),
 ('OMR Omani Rial', 'OMR Omani Rial'),
 ('PAB Panamanian Balboa', 'PAB Panamanian Balboa'),
 ('PEN Peruvian New Sol', 'PEN Peruvian New Sol'),
 ('PGK Papua New Guinea Kina', 'PGK Papua New Guinea Kina'),
 ('PHP Philippine Peso', 'PHP Philippine Peso'),
 ('PKR Pakistani Rupee', 'PKR Pakistani Rupee'),
 ('PLN Polish Zloty (new)', 'PLN Polish Zloty (new)'),
 ('PTE Portuguese Escudo', 'PTE Portuguese Escudo'),
 ('PYG Paraguayan Guarani', 'PYG Paraguayan Guarani'),
 ('QAR Qatar Rial', 'QAR Qatar Rial'),
 ('RMB Chinese Yuan Renminbi', 'RMB Chinese Yuan Renminbi'),
 ('ROL Romanian Leu', 'ROL Romanian Leu'),
 ('RUB Russian Ruble', 'RUB Russian Ruble'),
 ('RWF Rwandan Franc', 'RWF Rwandan Franc'),
 ('SAR Saudi Riyal', 'SAR Saudi Riyal'),
 ('SBD Solomon Islands Dollar', 'SBD Solomon Islands Dollar'),
 ('SCR Seychelles Rupee', 'SCR Seychelles Rupee'),
 ('SDP Sudanese Pound', 'SDP Sudanese Pound'),
 ('SEK Swedish Krona', 'SEK Swedish Krona'),
 ('SGD Singapore Dollar', 'SGD Singapore Dollar'),
 ('SHP St.Helena Pound', 'SHP St.Helena Pound'),
 ('SIT Slovenian Tolar', 'SIT Slovenian Tolar'),
 ('SKK Slovakian Krona', 'SKK Slovakian Krona'),
 ('SLL Sierra Leone Leone', 'SLL Sierra Leone Leone'),
 ('SOS Somalian Shilling', 'SOS Somalian Shilling'),
 ('SRG Surinam Guilder', 'SRG Surinam Guilder'),
 ('SSP South Sudanese Pound', 'SSP South Sudanese Pound'),
 ('STD Sao Tome / Principe Dobra', 'STD Sao Tome / Principe Dobra'),
 ('SVC El Salvador Colon', 'SVC El Salvador Colon'),
 ('SYP Syrian Pound', 'SYP Syrian Pound'),
 ('SZL Swaziland Lilangeni', 'SZL Swaziland Lilangeni'),
 ('THB Thailand Baht', 'THB Thailand Baht'),
 ('TJR Tajikistani Ruble', 'TJR Tajikistani Ruble'),
 ('TMM Turkmenistani Manat', 'TMM Turkmenistani Manat'),
 ('TND Tunisian Dinar', 'TND Tunisian Dinar'),
 ("TOP Tongan Pa'anga", "TOP Tongan Pa'anga"),
 ('TPE Timor Escudo', 'TPE Timor Escudo'),
 ('TRL Turkish Lira', 'TRL Turkish Lira'),
 ('TTD Trinidad and Tobago Dollar', 'TTD Trinidad and Tobago Dollar'),
 ('TWD New Taiwan Dollar', 'TWD New Taiwan Dollar'),
 ('TZS Tanzanian Shilling', 'TZS Tanzanian Shilling'),
 ('UAH Ukraine Hryvnia', 'UAH Ukraine Hryvnia'),
 ('UGX Ugandan Shilling', 'UGX Ugandan Shilling'),
 ('US6 American Dollar for six decimal places',
  'US6 American Dollar for six decimal places'),
 ('USC American Dollar Cents', 'USC American Dollar Cents'),
 ('USD United States Dollar', 'USD United States Dollar'),
 ('USDN (Internal) United States Dollar (5 Dec.)',
  'USDN (Internal) United States Dollar (5 Dec.)'),
 ('UYU Uruguayan Peso (new)', 'UYU Uruguayan Peso (new)'),
 ('UZS Uzbekistan Som', 'UZS Uzbekistan Som'),
 ('VEB Venezuelan Bolivar', 'VEB Venezuelan Bolivar'),
 ('VND Vietnamese Dong', 'VND Vietnamese Dong'),
 ('VUV Vanuatu Vatu', 'VUV Vanuatu Vatu'),
 ('WST Samoan Tala', 'WST Samoan Tala'),
 ('XAF Gabon CFA Franc BEAC', 'XAF Gabon CFA Franc BEAC'),
 ('XCD East Carribean Dollar', 'XCD East Carribean Dollar'),
 ('XDS St. Christopher Dollar', 'XDS St. Christopher Dollar'),
 ('XEU European Currency Unit (E.C.U.)',
  'XEU European Currency Unit (E.C.U.)'),
 ('XOF Benin CFA Franc BCEAO', 'XOF Benin CFA Franc BCEAO'),
 ('YER Yemeni Ryal', 'YER Yemeni Ryal'),
 ('YUM New Yugoslavian Dinar', 'YUM New Yugoslavian Dinar'),
 ('ZAR South African Rand', 'ZAR South African Rand'),
 ('ZMK Zambian Kwacha', 'ZMK Zambian Kwacha'),
 ('ZRN Zaire', 'ZRN Zaire'),
 ('ZWD Zimbabwean Dollar', 'ZWD Zimbabwean Dollar')]

payment_terms_list = [
(None,'Select Payment Terms'),
('01N Due 1 Day from Invoice Date', '01N Due 1 Day from Invoice Date'),('01P Due by the 1st of the Following Month','01P Due by the 1st of the Following Month'),
 ('02N Due 2 Days from Invoice Date', '02N Due 2 Days from Invoice Date'),('03N Due 3 Days from Invoice Date', '03N Due 3 Days from Invoice Date'),
 ('05N Due 5 Days from Invoice date', '05N Due 5 Days from Invoice date'),('05P Due by the 5th of following month','05P Due by the 5th of following month'),
 ('07N Due 7 Days from Invoice Date', '07N Due 7 Days from Invoice Date'),('10N Due 10 Days from Invoice date', '10N Due 10 Days from Invoice date'),
 ('13N Due 13 Days from Invoice Date', '13N Due 13 Days from Invoice Date'),('15N Due 15 Days from Invoice Date', '15N Due 15 Days from Invoice Date'),
 ('15P Due by the 15th of the Following Month','15P Due by the 15th of the Following Month'),('20N Due 20 Days from Invoice Date', '20N Due 20 Days from Invoice Date'),
 ('20P Due by the 20th of the Following Month','20P Due by the 20th of the Following Month'),('30N Due 30 Days from Invoice Date', '30N Due 30 Days from Invoice Date'),
 ('45N Due 45 Days from Invoice Date', '45N Due 45 Days from Invoice Date'),('60N Due 60 Days from Invoice Date', '60N Due 60 Days from Invoice Date'),
 ('COC Certified Cheque on Delivery', 'COC Certified Cheque on Delivery'),('COD Cash On Delivery', 'COD Cash On Delivery'),
 ('JV15 JV only: posting date + 15 days','JV15 JV only: posting date + 15 days'),('JV30 JV only: posting date + 30 days','JV30 JV only: posting date + 30 days'),
 ('Z000 Pay immediately w/o deduction (post date) - USE COD','Z000 Pay immediately w/o deduction (post date) - USE COD'),('Z001 NET 25TH OF MONTH FOLLOWING - USE 25P','Z001 NET 25TH OF MONTH FOLLOWING - USE 25P'),
 ('Z002 DNU NET 20TH OF MONTH FOLLOWING','Z002 DNU NET 20TH OF MONTH FOLLOWING'),('Z003 Net 5 Days: Entry Date + 5 day - USE 05N','Z003 Net 5 Days: Entry Date + 5 day - USE 05N'),
 ('Z004 Net 7 Days: Entry Date + 7 day - USE 07N','Z004 Net 7 Days: Entry Date + 7 day - USE 07N'),
 ('Z005 Net 10 Days: Entry Date + 10 day - USE 10N','Z005 Net 10 Days: Entry Date + 10 day - USE 10N'),('Z006 Net 15 Days: Entry Date + 15 day - USE 15N','Z006 Net 15 Days: Entry Date + 15 day - USE 15N'),
 ('Z007 Net 20 Days: Entry Date + 20 day - USE 20N','Z007 Net 20 Days: Entry Date + 20 day - USE 20N'),('Z008 Net 30 Days: Entry Date + 30 day - USE 30N','Z008 Net 30 Days: Entry Date + 30 day - USE 30N'),
 ('Z009 Net 40 Days: Entry Date + 40 day - USE 40N','Z009 Net 40 Days: Entry Date + 40 day - USE 40N'),('Z010 Net 45 Days: Entry Date + 45 day - USE 45N','Z010 Net 45 Days: Entry Date + 45 day - USE 45N'),
 ('Z011 Net 60 Days: Entry Date + 60 day - USE 60N','Z011 Net 60 Days: Entry Date + 60 day - USE 60N'),('Z012 Last Day of Month', 'Z012 Last Day of Month'),
 ('Z014 1% 10 Days, Net 30', 'Z014 1% 10 Days, Net 30'),('Z020 2% 10 Days, Net 30', 'Z020 2% 10 Days, Net 30'),
 ('Z025 2% 10 Days, Net 45', 'Z025 2% 10 Days, Net 45'),('Z026 Net 15th of the Month', 'Z026 Net 15th of the Month'),('Z027 Net 25th of the Month', 'Z027 Net 25th of the Month'),
 ('Z028 3% 10 Days, Net 30', 'Z028 3% 10 Days, Net 30'),('Z029 Net 15th or end of Month', 'Z029 Net 15th or end of Month'),('Z030 0.35% 10 Days, Net 30', 'Z030 0.35% 10 Days, Net 30'),
 ('Z096 Net 1 Day: Entry Date + 1 day', 'Z096 Net 1 Day: Entry Date + 1 day'),('Z097 Net 2 Days: Entry Date + 2 days','Z097 Net 2 Days: Entry Date + 2 days'),
 ('Z098 Net 3 Days: Entry Date + 3 days','Z098 Net 3 Days: Entry Date + 3 days'),('Z104 Discount 2200 N10 1%', 'Z104 Discount 2200 N10 1%')]

reasons_for_outside_list = [(None, 'Select a Reason for Payment Terms outside of 60N'), ('Director approval','Director approval'), ('Brokerage fees','Brokerage fees'),
                        ('Charitable donations','Charitable donations'),('Direct taxation, including royalties','Direct taxation, including royalties'),
                        ('Emission carbon allowance purchases','Emission carbon allowance purchases'),('Employee reimbursable expenses (including interview expenses)','Employee reimbursable expenses (including interview expenses)'),
                        ('Hydrocarbon logistics costs','Hydrocarbon logistics costs'),('Hydrocarbon logistics costs','Hydrocarbon logistics costs'),
                        ('Hydrocarbon purchases','Hydrocarbon purchases'),('Insurance coverage','Insurance coverage'),('Land leases','Land leases'),
                        ('Marketing sponsorships','Marketing sponsorships'),('Partnership funding','Partnership funding'),('Payroll related remittances','Payroll related remittances'),
                        ('Utilities','Utilities')]

form5_items_dict = {
        'form5_1':'This CSA request form is for purely an administrative change to an existing contract',
        'form5_2':'This contract is purely for professional services',
        'form5_3':'The contract is a take-or-pay arrangement or is there a significant cost to Suncor in the event of early contract termination that is an exception/deviation from the standard termination of convenience language around compensation following termination',
        'form5_4':'The contract is a purchase contract where full payment is made within 1 year',
        'form5_5':'The contract is cancellable by both parties with 30 days notice',
        'form5_6':'The contract term, including all extensions possible, is less than 30 days',
        'form5_7':'The contract is for services, where any assets used to provide the service that are owned by the contractor are used for a limited time',
        'form5_8':'The contract is for one of the following asset types: bulldozers or railway cars',
        'form5_9':'The contract is for one of the following asset types: Buildings (including office space & warehouses) or marine vessels',
        'form5_10':'The contract is for one of the following asset types: Fleet vehicles (e.g. Element or Driving force) or office printers',
        'form5_11':'The contract is for services, where the assets used to provide the service are owned by Suncor',
        'form5_12':'The contract is for services, where the assets used to provide the service that are owned by the contractor are of low value',
        'form5_13':'The contract is for services, where any assets used to provide the service that are owned by the contractor are interchangeable',
        'form5_14':'The asset (e.g. equipment, machinery, trucks) is also currently used by other companies & Suncor uses less than 75% of the available capacity',
        'form5_15':'The contract is for an intangible asset'
}

incoterms_list = [(None, 'Select Inco-Term'),
 ('N/A (For Service Contracts)', 'N/A (For Service Contracts)'),
 ('A01 SERV U TO DESTINATION', 'A01 SERV U TO DESTINATION'),
 ('A03 GRIMSHAW TO DESTINATION', 'A03 GRIMSHAW TO DESTINATION'),
 ('A05 D&R TO GRIMSHAW EDM TO DEST', 'A05 D&R TO GRIMSHAW EDM TO DEST'),
 ('A06 D&R TO DESTINATION', 'A06 D&R TO DESTINATION'),
 ('A07 FDXFSTFRT C/O D&R TO GRIM EDM', 'A07 FDXFSTFRT C/O D&R TO GRIM EDM'),
 ('A08 WESTFRT TO GRIMS EDM TO DEST', 'A08 WESTFRT TO GRIMS EDM TO DEST'),
 ('A09 WESTFREIGHT TO DESTINATION', 'A09 WESTFREIGHT TO DESTINATION'),
 ('A10 MULLEN TO GRIMS EDM TO DEST', 'A10 MULLEN TO GRIMS EDM TO DEST'),
 ('A11 MULLEN TO DESTINATION', 'A11 MULLEN TO DESTINATION'),
 ('A12 PREMAY TO DESTINATION', 'A12 PREMAY TO DESTINATION'),
 ('A13 REIMER BULK TO DESTINATION', 'A13 REIMER BULK TO DESTINATION'),
 ('A14 HWY9 TO GRIM EDM TO DESTINATIO', 'A14 HWY9 TO GRIM EDM TO DESTINATIO'),
 ('A15 GOLOSKY TO DESTINATION', 'A15 GOLOSKY TO DESTINATION'),
 ('A16 FANDRICKS TO GIBSON PETR EDM', 'A16 FANDRICKS TO GIBSON PETR EDM'),
 ('A17 MEL MARTIN TO GRIM EDM TO DEST', 'A17 MEL MARTIN TO GRIM EDM TO DEST'),
 ('A18 UPS TO EDM HOLD GRIM TO DEST', 'A18 UPS TO EDM HOLD GRIM TO DEST'),
 ('A19 UPS TO EDM HOLD GRIM TO DEST', 'A19 UPS TO EDM HOLD GRIM TO DEST'),
 ('A20 UPS TO EDM HOLD GRIM TO DEST', 'A20 UPS TO EDM HOLD GRIM TO DEST'),
 ('A21 UPS GOLD EDM DYN AIR CAN FMCM', 'A21 UPS GOLD EDM DYN AIR CAN FMCM'),
 ('A22 UPS GOLD TO DESTINATION', 'A22 UPS GOLD TO DESTINATION'),
 ('A23 UPS AM TO DESTINATION', 'A23 UPS AM TO DESTINATION'),
 ('A24 UPS TO EDM HOLD GRIM TO DEST', 'A24 UPS TO EDM HOLD GRIM TO DEST'),
 ('A25 AIR CAN GUARANTEED TO DEST', 'A25 AIR CAN GUARANTEED TO DEST'),
 ('A27 AIR CAN REG TO EDM GRIM DEST', 'A27 AIR CAN REG TO EDM GRIM DEST'),
 ('A28 AIR CAN REG TO DESTINATION', 'A28 AIR CAN REG TO DESTINATION'),
 ('A29 WESTJET GUARANTEED TO DEST', 'A29 WESTJET GUARANTEED TO DEST'),
 ('A31 WESTJET REG EDM GRIM TO DEST', 'A31 WESTJET REG EDM GRIM TO DEST'),
 ('A32 WESTJET REG TO DESTINATION', 'A32 WESTJET REG TO DESTINATION'),
 ('A34 DYN TO GRIM WHSE GRIM TO DEST', 'A34 DYN TO GRIM WHSE GRIM TO DEST'),
 ('A35 DYN TO AIR CAN AIR CAN TO DEST', 'A35 DYN TO AIR CAN AIR CAN TO DEST'),
 ('A36 DYNAMEX TO WESTJET', 'A36 DYNAMEX TO WESTJET'),
 ('A37 DYNAMEX TO DESTINATION', 'A37 DYNAMEX TO DESTINATION'),
 ('A38 DYNAMEX REG TO DESTINATION', 'A38 DYNAMEX REG TO DESTINATION'),
 ('A40 DHL-COURIER TO DESTINATION', 'A40 DHL-COURIER TO DESTINATION'),
 ('A41 FEDEX-COURIER TO DESTINATION', 'A41 FEDEX-COURIER TO DESTINATION'),
 ('A42 LOOMIS-COURIER TO DESTINATION', 'A42 LOOMIS-COURIER TO DESTINATION'),
 ('A43 PURO TO FMCM - SERVU TO DEST', 'A43 PURO TO FMCM - SERVU TO DEST'),
 ('A44 SHOULD BE CPT', 'A44 SHOULD BE CPT'),
 ('A45 VPP TO GRIMSHAW EDM TO DEST', 'A45 VPP TO GRIMSHAW EDM TO DEST'),
 ('A46 COLE FREIGHT - CALL PRIOR', 'A46 COLE FREIGHT - CALL PRIOR'),
 ('A47 CALL SUNCOR TRANS SHIP INSTRUC', 'A47 CALL SUNCOR TRANS SHIP INSTRUC'),
 ('A48 EXPRESS MAIL TO FT MCMURRAY', 'A48 EXPRESS MAIL TO FT MCMURRAY'),
 ('A49 TRANSPORTATION NOT APPLICABLE', 'A49 TRANSPORTATION NOT APPLICABLE'),
 ('A50 2 WKS PRIOR TO SHIP CALL COLE', 'A50 2 WKS PRIOR TO SHIP CALL COLE'),
 ('A51 SEE BELOW FOR INSTRUCTIONS', 'A51 SEE BELOW FOR INSTRUCTIONS'),
 ('A52 CAN FRE TO HBT WH TO HBT SITE', 'A52 CAN FRE TO HBT WH TO HBT SITE'),
 ('A53 CAN FREIGHTWAYS TO FORT HILLS', 'A53 CAN FREIGHTWAYS TO FORT HILLS'),
 ('A60 RYDER TO DESTINATION', 'A60 RYDER TO DESTINATION'),
 ('A61 MANITOULIN TO RYDER EDM TO DES', 'A61 MANITOULIN TO RYDER EDM TO DES'),
 ('A62 WESTFRT TO RYDER EDM TO DEST', 'A62 WESTFRT TO RYDER EDM TO DEST'),
 ('A63 HWY9 TO RYDER EDM TO DEST', 'A63 HWY9 TO RYDER EDM TO DEST'),
 ('A64 MEL MARTIN TO RYDER EDM TO DES', 'A64 MEL MARTIN TO RYDER EDM TO DES'),
 ('A65 CADFRTWAY TO RYDER EDM TO DEST', 'A65 CADFRTWAY TO RYDER EDM TO DEST'),
 ('B46 COLE FREIGHT - CALL PRIOR', 'B46 COLE FREIGHT - CALL PRIOR'),
 ('B47 CALL SUNCOR TRANS SHIP INSTRUC', 'B47 CALL SUNCOR TRANS SHIP INSTRUC'),
 ('B48 EXPRESS MAIL TO FT MCMURRAY', 'B48 EXPRESS MAIL TO FT MCMURRAY'),
 ('B49 TRANSPORTATION NOT APPLICABLE', 'B49 TRANSPORTATION NOT APPLICABLE'),
 ('B50 2 WKS PRIOR TO SHIP CALL COLE', 'B50 2 WKS PRIOR TO SHIP CALL COLE'),
 ('B51 SEE BELOW FOR INSTRUCTIONS', 'B51 SEE BELOW FOR INSTRUCTIONS'),
 ('CFR Cost and Freight', 'CFR Cost and Freight'),
 ('CIF Cost, Insurance and Freight', 'CIF Cost, Insurance and Freight'),
 ('CIP Carriage and Insurance Paid To', 'CIP Carriage and Insurance Paid To'),
 ('CPT Carriage Paid To', 'CPT Carriage Paid To'),
 ('D01 SERV U TO DESTINATION', 'D01 SERV U TO DESTINATION'),
 ('D02 RYDER TO DESTINATION', 'D02 RYDER TO DESTINATION'),
 ('D03 GRIMSHAW TO DESTINATION', 'D03 GRIMSHAW TO DESTINATION'),
 ('D05 D&R TO GRIMSHAW EDM TO DEST', 'D05 D&R TO GRIMSHAW EDM TO DEST'),
 ('D06 D&R TO DESTINATION', 'D06 D&R TO DESTINATION'),
 ('D14 HWY9 TO GRIM EDM TO DESTINATIO', 'D14 HWY9 TO GRIM EDM TO DESTINATIO'),
 ('D17 MEL MARTIN TO GRIM EDM TO DEST', 'D17 MEL MARTIN TO GRIM EDM TO DEST'),
 ('D18 UPS TO EDM HOLD GRIM TO DEST', 'D18 UPS TO EDM HOLD GRIM TO DEST'),
 ('D19 UPS TO EDM HOLD GRIM TO DEST', 'D19 UPS TO EDM HOLD GRIM TO DEST'),
 ('D20 UPS TO EDM HOLD GRIM TO DEST', 'D20 UPS TO EDM HOLD GRIM TO DEST'),
 ('D21 UPS GOLD EDM DYN AIR CAN FMCM', 'D21 UPS GOLD EDM DYN AIR CAN FMCM'),
 ('D22 UPS GOLD TO DESTINATION', 'D22 UPS GOLD TO DESTINATION'),
 ('D23 UPS AM TO DESTINATION', 'D23 UPS AM TO DESTINATION'),
 ('D24 UPS TO EDM HOLD GRIM TO DEST', 'D24 UPS TO EDM HOLD GRIM TO DEST'),
 ('D25 AIR CAN GUARANTEED TO DEST', 'D25 AIR CAN GUARANTEED TO DEST'),
 ('D27 AIR CAN REG TO EDM GRIM DEST', 'D27 AIR CAN REG TO EDM GRIM DEST'),
 ('D28 AIR CAN REG TO DESTINATION', 'D28 AIR CAN REG TO DESTINATION'),
 ('D29 WESTJET GUARANTEED TO DEST', 'D29 WESTJET GUARANTEED TO DEST'),
 ('D31 WESTJET REG EDM GRIM TO DEST', 'D31 WESTJET REG EDM GRIM TO DEST'),
 ('D32 WESTJET REG TO DESTINATION', 'D32 WESTJET REG TO DESTINATION'),
 ('D34 DYN TO GRIM WHSE GRIM TO DEST', 'D34 DYN TO GRIM WHSE GRIM TO DEST'),
 ('D35 DYN TO AIR CAN AIR CAN TO DEST', 'D35 DYN TO AIR CAN AIR CAN TO DEST'),
 ('D36 DYNAMEX TO WESTJET', 'D36 DYNAMEX TO WESTJET'),
 ('D37 DYNAMEX TO DESTINATION', 'D37 DYNAMEX TO DESTINATION'),
 ('D38 DYNAMEX REG TO DESTINATION', 'D38 DYNAMEX REG TO DESTINATION'),
 ('D44 SHOULD BE CPT', 'D44 SHOULD BE CPT'),
 ('D45 VPP TO GRIMSHAW EDM TO DEST', 'D45 VPP TO GRIMSHAW EDM TO DEST'),
 ('D46 COLE FREIGHT - CALL PRIOR', 'D46 COLE FREIGHT - CALL PRIOR'),
 ('D47 CALL SUNCOR TRANS SHIP INSTRUC', 'D47 CALL SUNCOR TRANS SHIP INSTRUC'),
 ('D48 EXPRESS MAIL TO FT MCMURRAY', 'D48 EXPRESS MAIL TO FT MCMURRAY'),
 ('D49 TRANSPORTATION NOT APPLICABLE', 'D49 TRANSPORTATION NOT APPLICABLE'),
 ('D50 2 WKS PRIOR TO SHIP CALL COLE', 'D50 2 WKS PRIOR TO SHIP CALL COLE'),
 ('D51 SEE BELOW FOR INSTRUCTIONS', 'D51 SEE BELOW FOR INSTRUCTIONS'),
 ('D52 AIR CAN REG TO EDM RYDER TO DE', 'D52 AIR CAN REG TO EDM RYDER TO DE'),
 ('DAF Delivered at Frontier', 'DAF Delivered at Frontier'),
 ('DAP Delivered at Place', 'DAP Delivered at Place'),
 ('DAT Delivered at Terminal', 'DAT Delivered at Terminal'),
 ('DDP Delivered Duty Paid', 'DDP Delivered Duty Paid'),
 ('DDU Delivered Duty Unpaid', 'DDU Delivered Duty Unpaid'),
 ('DEQ Delivered Ex Quay (Duty Paid)', 'DEQ Delivered Ex Quay (Duty Paid)'),
 ('DES Delivered Ex Ship', 'DES Delivered Ex Ship'),
 ('E01 SERV U TO DESTINATION', 'E01 SERV U TO DESTINATION'),
 ('E02 RYDER TO DESTINATION', 'E02 RYDER TO DESTINATION'),
 ('E03 GRIMSHAW TO DESTINATION', 'E03 GRIMSHAW TO DESTINATION'),
 ('E04 MANITOULIN TO RYDER EDM TO DES', 'E04 MANITOULIN TO RYDER EDM TO DES'),
 ('E05 D&R TO GRIMSHAW EDM TO DEST', 'E05 D&R TO GRIMSHAW EDM TO DEST'),
 ('E06 D&R TO DESTINATION', 'E06 D&R TO DESTINATION'),
 ('E07 FDXFSTFRT C/O D&R TO GRIM EDM', 'E07 FDXFSTFRT C/O D&R TO GRIM EDM'),
 ('E08 WESTFRT TO GRIMS EDM TO DEST', 'E08 WESTFRT TO GRIMS EDM TO DEST'),
 ('E09 WESTFREIGHT TO DESTINATION', 'E09 WESTFREIGHT TO DESTINATION'),
 ('E10 MULLEN TO GRIMS EDM TO DEST', 'E10 MULLEN TO GRIMS EDM TO DEST'),
 ('E11 MULLEN TO DESTINATION', 'E11 MULLEN TO DESTINATION'),
 ('E12 PREMAY TO DESTINATION', 'E12 PREMAY TO DESTINATION'),
 ('E13 REIMER BULK TO DESTINATION', 'E13 REIMER BULK TO DESTINATION'),
 ('E14 HWY9 TO GRIM EDM TO DESTINATIO', 'E14 HWY9 TO GRIM EDM TO DESTINATIO'),
 ('E15 GOLOSKY TO DESTINATION', 'E15 GOLOSKY TO DESTINATION'),
 ('E16 FANDRICKS TO GIBSON PETR EDM', 'E16 FANDRICKS TO GIBSON PETR EDM'),
 ('E17 MEL MARTIN TO GRIM EDM TO DEST', 'E17 MEL MARTIN TO GRIM EDM TO DEST'),
 ('E18 UPS TO EDM HOLD GRIM TO DEST', 'E18 UPS TO EDM HOLD GRIM TO DEST'),
 ('E19 UPS TO EDM HOLD GRIM TO DEST', 'E19 UPS TO EDM HOLD GRIM TO DEST'),
 ('E20 UPS TO EDM HOLD GRIM TO DEST', 'E20 UPS TO EDM HOLD GRIM TO DEST'),
 ('E21 UPS GOLD EDM DYN AIR CAN FMCM', 'E21 UPS GOLD EDM DYN AIR CAN FMCM'),
 ('E22 UPS GOLD TO DESTINATION', 'E22 UPS GOLD TO DESTINATION'),
 ('E23 UPS AM TO DESTINATION', 'E23 UPS AM TO DESTINATION'),
 ('E24 UPS TO EDM HOLD GRIM TO DEST', 'E24 UPS TO EDM HOLD GRIM TO DEST'),
 ('E25 AIR CAN GUARANTEED TO DEST', 'E25 AIR CAN GUARANTEED TO DEST'),
 ('E27 AIR CAN REG TO EDM GRIM DEST', 'E27 AIR CAN REG TO EDM GRIM DEST'),
 ('E28 AIR CAN REG TO DESTINATION', 'E28 AIR CAN REG TO DESTINATION'),
 ('E29 WESTJET GUARANTEED TO DEST', 'E29 WESTJET GUARANTEED TO DEST'),
 ('E30 CADFRTWAY TO RYDER EDM TO DEST', 'E30 CADFRTWAY TO RYDER EDM TO DEST'),
 ('E31 WESTJET REG EDM GRIM TO DEST', 'E31 WESTJET REG EDM GRIM TO DEST'),
 ('E32 WESTJET REG TO DESTINATION', 'E32 WESTJET REG TO DESTINATION'),
 ('E34 DYN TO GRIM WHSE GRIM TO DEST', 'E34 DYN TO GRIM WHSE GRIM TO DEST'),
 ('E35 DYN TO AIR CAN AIR CAN TO DEST', 'E35 DYN TO AIR CAN AIR CAN TO DEST'),
 ('E36 DYNAMEX TO WESTJET', 'E36 DYNAMEX TO WESTJET'),
 ('E37 DYNAMEX TO DESTINATION', 'E37 DYNAMEX TO DESTINATION'),
 ('E38 DYNAMEX REG TO DESTINATION', 'E38 DYNAMEX REG TO DESTINATION'),
 ('E40 DHL-COURIER TO DESTINATION', 'E40 DHL-COURIER TO DESTINATION'),
 ('E41 FEDEX-COURIER TO DESTINATION', 'E41 FEDEX-COURIER TO DESTINATION'),
 ('E42 LOOMIS-COURIER TO DESTINATION', 'E42 LOOMIS-COURIER TO DESTINATION'),
 ('E43 PURO TO FMCM - SERVU TO DEST', 'E43 PURO TO FMCM - SERVU TO DEST'),
 ('E44 SHOULD BE CPT', 'E44 SHOULD BE CPT'),
 ('E45 VPP TO GRIMSHAW EDM TO DEST', 'E45 VPP TO GRIMSHAW EDM TO DEST'),
 ('E46 COLE FREIGHT - CALL PRIOR', 'E46 COLE FREIGHT - CALL PRIOR'),
 ('E47 CALL SUNCOR TRANS SHIP INSTRUC', 'E47 CALL SUNCOR TRANS SHIP INSTRUC'),
 ('E48 EXPRESS MAIL TO FT MCMURRAY', 'E48 EXPRESS MAIL TO FT MCMURRAY'),
 ('E49 TRANSPORTATION NOT APPLICABLE', 'E49 TRANSPORTATION NOT APPLICABLE'),
 ('E50 2 WKS PRIOR TO SHIP CALL COLE', 'E50 2 WKS PRIOR TO SHIP CALL COLE'),
 ('E51 SEE BELOW FOR INSTRUCTIONS', 'E51 SEE BELOW FOR INSTRUCTIONS'),
 ('EXW Ex Works', 'EXW Ex Works'),
 ('F08 WESTFRT TO GRIMS EDM TO DEST', 'F08 WESTFRT TO GRIMS EDM TO DEST'),
 ('F09 WESTFREIGHT TO DESTINATION', 'F09 WESTFREIGHT TO DESTINATION'),
 ('F10 MULLEN TO GRIMS EDM TO DEST', 'F10 MULLEN TO GRIMS EDM TO DEST'),
 ('F11 MULLEN TO DESTINATION', 'F11 MULLEN TO DESTINATION'),
 ('F12 PREMAY TO DESTINATION', 'F12 PREMAY TO DESTINATION'),
 ('F15 GOLOSKY TO DESTINATION', 'F15 GOLOSKY TO DESTINATION'),
 ('F34 DYN TO GRIM WHSE GRIM TO DEST', 'F34 DYN TO GRIM WHSE GRIM TO DEST'),
 ('F35 DYN TO AIR CAN AIR CAN TO DEST', 'F35 DYN TO AIR CAN AIR CAN TO DEST'),
 ('F36 DYNAMEX TO WESTJET', 'F36 DYNAMEX TO WESTJET'),
 ('F37 DYNAMEX TO DESTINATION', 'F37 DYNAMEX TO DESTINATION'),
 ('F38 DYNAMEX REG TO DESTINATION', 'F38 DYNAMEX REG TO DESTINATION'),
 ('F44 SHOULD BE CPT', 'F44 SHOULD BE CPT'),
 ('F45 VPP TO GRIMSHAW EDM TO DEST', 'F45 VPP TO GRIMSHAW EDM TO DEST'),
 ('F46 COLE FREIGHT - CALL PRIOR', 'F46 COLE FREIGHT - CALL PRIOR'),
 ('F47 CALL SUNCOR TRANS SHIP INSTRUC', 'F47 CALL SUNCOR TRANS SHIP INSTRUC'),
 ('F48 EXPRESS MAIL TO FT MCMURRAY', 'F48 EXPRESS MAIL TO FT MCMURRAY'),
 ('F49 TRANSPORTATION NOT APPLICABLE', 'F49 TRANSPORTATION NOT APPLICABLE'),
 ('F50 2 WKS PRIOR TO SHIP CALL COLE', 'F50 2 WKS PRIOR TO SHIP CALL COLE'),
 ('F51 SEE BELOW FOR INSTRUCTIONS', 'F51 SEE BELOW FOR INSTRUCTIONS'),
 ('FAS Free Alongside Ship', 'FAS Free Alongside Ship'),
 ('FCA Free Carrier', 'FCA Free Carrier'),
 ('FH Free House', 'FH Free House'),
 ('FOB Free On Board', 'FOB Free On Board'),
 ('G08 WESTFRT TO GRIMS EDM TO DEST', 'G08 WESTFRT TO GRIMS EDM TO DEST'),
 ('G09 WESTFREIGHT TO DESTINATION', 'G09 WESTFREIGHT TO DESTINATION'),
 ('G10 MULLEN TO GRIMS EDM TO DEST', 'G10 MULLEN TO GRIMS EDM TO DEST'),
 ('G11 MULLEN TO DESTINATION', 'G11 MULLEN TO DESTINATION'),
 ('G12 PREMAY TO DESTINATION', 'G12 PREMAY TO DESTINATION'),
 ('G15 GOLOSKY TO DESTINATION', 'G15 GOLOSKY TO DESTINATION'),
 ('G34 DYN TO GRIM WHSE GRIM TO DEST', 'G34 DYN TO GRIM WHSE GRIM TO DEST'),
 ('G35 DYN TO AIR CAN AIR CAN TO DEST', 'G35 DYN TO AIR CAN AIR CAN TO DEST'),
 ('G36 DYNAMEX TO WESTJET', 'G36 DYNAMEX TO WESTJET'),
 ('G37 DYNAMEX TO DESTINATION', 'G37 DYNAMEX TO DESTINATION'),
 ('G38 DYNAMEX REG TO DESTINATION', 'G38 DYNAMEX REG TO DESTINATION'),
 ('G44 SHOULD BE CPT', 'G44 SHOULD BE CPT'),
 ('G45 VPP TO GRIMSHAW EDM TO DEST', 'G45 VPP TO GRIMSHAW EDM TO DEST'),
 ('G46 COLE FREIGHT - CALL PRIOR', 'G46 COLE FREIGHT - CALL PRIOR'),
 ('G47 CALL SUNCOR TRANS SHIP INSTRUC', 'G47 CALL SUNCOR TRANS SHIP INSTRUC'),
 ('G48 EXPRESS MAIL TO FT MCMURRAY', 'G48 EXPRESS MAIL TO FT MCMURRAY'),
 ('G49 TRANSPORTATION NOT APPLICABLE', 'G49 TRANSPORTATION NOT APPLICABLE'),
 ('G50 2 WKS PRIOR TO SHIP CALL COLE', 'G50 2 WKS PRIOR TO SHIP CALL COLE'),
 ('G51 SEE BELOW FOR INSTRUCTIONS', 'G51 SEE BELOW FOR INSTRUCTIONS'),
 ('J08 WESTFRT TO GRIMS EDM TO DEST', 'J08 WESTFRT TO GRIMS EDM TO DEST'),
 ('J09 WESTFREIGHT TO DESTINATION', 'J09 WESTFREIGHT TO DESTINATION'),
 ('J10 MULLEN TO GRIMS EDM TO DEST', 'J10 MULLEN TO GRIMS EDM TO DEST'),
 ('J11 MULLEN TO DESTINATION', 'J11 MULLEN TO DESTINATION'),
 ('J12 PREMAY TO DESTINATION', 'J12 PREMAY TO DESTINATION'),
 ('J15 GOLOSKY TO DESTINATION', 'J15 GOLOSKY TO DESTINATION'),
 ('J34 DYN TO GRIM WHSE GRIM TO DEST', 'J34 DYN TO GRIM WHSE GRIM TO DEST'),
 ('J35 DYN TO AIR CAN AIR CAN TO DEST', 'J35 DYN TO AIR CAN AIR CAN TO DEST'),
 ('J36 DYNAMEX TO WESTJET', 'J36 DYNAMEX TO WESTJET'),
 ('J37 DYNAMEX TO DESTINATION', 'J37 DYNAMEX TO DESTINATION'),
 ('J38 DYNAMEX REG TO DESTINATION', 'J38 DYNAMEX REG TO DESTINATION'),
 ('J44 SHOULD BE CPT', 'J44 SHOULD BE CPT'),
 ('J45 VPP TO GRIMSHAW EDM TO DEST', 'J45 VPP TO GRIMSHAW EDM TO DEST'),
 ('J46 COLE FREIGHT - CALL PRIOR', 'J46 COLE FREIGHT - CALL PRIOR'),
 ('J47 CALL SUNCOR TRANS SHIP INSTRUC', 'J47 CALL SUNCOR TRANS SHIP INSTRUC'),
 ('J48 EXPRESS MAIL TO FT MCMURRAY', 'J48 EXPRESS MAIL TO FT MCMURRAY'),
 ('J49 TRANSPORTATION NOT APPLICABLE', 'J49 TRANSPORTATION NOT APPLICABLE'),
 ('J50 2 WKS PRIOR TO SHIP CALL COLE', 'J50 2 WKS PRIOR TO SHIP CALL COLE'),
 ('J51 SEE BELOW FOR INSTRUCTIONS', 'J51 SEE BELOW FOR INSTRUCTIONS'),
 ('NRC No Charge', 'NRC No Charge'),
 ('P07 WESTFRT TO RYDER EDM TO DEST', 'P07 WESTFRT TO RYDER EDM TO DEST'),
 ('P08 WESTFRT TO GRIMS EDM TO DEST', 'P08 WESTFRT TO GRIMS EDM TO DEST'),
 ('P09 WESTFREIGHT TO DESTINATION', 'P09 WESTFREIGHT TO DESTINATION'),
 ('P10 MULLEN TO GRIMS EDM TO DEST', 'P10 MULLEN TO GRIMS EDM TO DEST'),
 ('P11 MULLEN TO DESTINATION', 'P11 MULLEN TO DESTINATION'),
 ('P12 PREMAY TO DESTINATION', 'P12 PREMAY TO DESTINATION'),
 ('P15 GOLOSKY TO DESTINATION', 'P15 GOLOSKY TO DESTINATION'),
 ('P34 DYN TO GRIM WHSE GRIM TO DEST', 'P34 DYN TO GRIM WHSE GRIM TO DEST'),
 ('P35 DYN TO AIR CAN AIR CAN TO DEST', 'P35 DYN TO AIR CAN AIR CAN TO DEST'),
 ('P36 DYNAMEX TO WESTJET', 'P36 DYNAMEX TO WESTJET'),
 ('P37 DYNAMEX TO DESTINATION', 'P37 DYNAMEX TO DESTINATION'),
 ('P38 DYNAMEX REG TO DESTINATION', 'P38 DYNAMEX REG TO DESTINATION'),
 ('P44 SHOULD BE CPT', 'P44 SHOULD BE CPT'),
 ('P45 VPP TO GRIMSHAW EDM TO DEST', 'P45 VPP TO GRIMSHAW EDM TO DEST'),
 ('P46 COLE FREIGHT - CALL PRIOR', 'P46 COLE FREIGHT - CALL PRIOR'),
 ('P47 CALL SUNCOR TRANS SHIP INSTRUC', 'P47 CALL SUNCOR TRANS SHIP INSTRUC'),
 ('P48 EXPRESS MAIL TO FT MCMURRAY', 'P48 EXPRESS MAIL TO FT MCMURRAY'),
 ('P49 TRANSPORTATION NOT APPLICABLE', 'P49 TRANSPORTATION NOT APPLICABLE'),
 ('P50 2 WKS PRIOR TO SHIP CALL COLE', 'P50 2 WKS PRIOR TO SHIP CALL COLE'),
 ('P51 SEE BELOW FOR INSTRUCTIONS', 'P51 SEE BELOW FOR INSTRUCTIONS'),
 ('Q08 WESTFRT TO GRIMS EDM TO DEST', 'Q08 WESTFRT TO GRIMS EDM TO DEST'),
 ('Q09 WESTFREIGHT TO DESTINATION', 'Q09 WESTFREIGHT TO DESTINATION'),
 ('Q10 MULLEN TO GRIMS EDM TO DEST', 'Q10 MULLEN TO GRIMS EDM TO DEST'),
 ('Q11 MULLEN TO DESTINATION', 'Q11 MULLEN TO DESTINATION'),
 ('Q12 PREMAY TO DESTINATION', 'Q12 PREMAY TO DESTINATION'),
 ('Q15 GOLOSKY TO DESTINATION', 'Q15 GOLOSKY TO DESTINATION'),
 ('Q34 DYN TO GRIM WHSE GRIM TO DEST', 'Q34 DYN TO GRIM WHSE GRIM TO DEST'),
 ('Q35 DYN TO AIR CAN AIR CAN TO DEST', 'Q35 DYN TO AIR CAN AIR CAN TO DEST'),
 ('Q36 DYNAMEX TO WESTJET', 'Q36 DYNAMEX TO WESTJET'),
 ('Q37 DYNAMEX TO DESTINATION', 'Q37 DYNAMEX TO DESTINATION'),
 ('Q38 DYNAMEX REG TO DESTINATION', 'Q38 DYNAMEX REG TO DESTINATION'),
 ('Q44 SHOULD BE CPT', 'Q44 SHOULD BE CPT'),
 ('Q45 VPP TO GRIMSHAW EDM TO DEST', 'Q45 VPP TO GRIMSHAW EDM TO DEST'),
 ('Q46 COLE FREIGHT - CALL PRIOR', 'Q46 COLE FREIGHT - CALL PRIOR'),
 ('Q47 CALL SUNCOR TRANS SHIP INSTRUC', 'Q47 CALL SUNCOR TRANS SHIP INSTRUC'),
 ('Q48 EXPRESS MAIL TO FT MCMURRAY', 'Q48 EXPRESS MAIL TO FT MCMURRAY'),
 ('Q49 TRANSPORTATION NOT APPLICABLE', 'Q49 TRANSPORTATION NOT APPLICABLE'),
 ('Q50 2 WKS PRIOR TO SHIP CALL COLE', 'Q50 2 WKS PRIOR TO SHIP CALL COLE'),
 ('Q51 SEE BELOW FOR INSTRUCTIONS', 'Q51 SEE BELOW FOR INSTRUCTIONS'),
 ('R08 WESTFRT TO GRIMS EDM TO DEST', 'R08 WESTFRT TO GRIMS EDM TO DEST'),
 ('R09 WESTFREIGHT TO DESTINATION', 'R09 WESTFREIGHT TO DESTINATION'),
 ('R10 MULLEN TO GRIMS EDM TO DEST', 'R10 MULLEN TO GRIMS EDM TO DEST'),
 ('R11 MULLEN TO DESTINATION', 'R11 MULLEN TO DESTINATION'),
 ('R12 PREMAY TO DESTINATION', 'R12 PREMAY TO DESTINATION'),
 ('R15 GOLOSKY TO DESTINATION', 'R15 GOLOSKY TO DESTINATION'),
 ('R34 DYN TO GRIM WHSE GRIM TO DEST', 'R34 DYN TO GRIM WHSE GRIM TO DEST'),
 ('R35 DYN TO AIR CAN AIR CAN TO DEST', 'R35 DYN TO AIR CAN AIR CAN TO DEST'),
 ('R36 DYNAMEX TO WESTJET', 'R36 DYNAMEX TO WESTJET'),
 ('R37 DYNAMEX TO DESTINATION', 'R37 DYNAMEX TO DESTINATION'),
 ('R38 DYNAMEX REG TO DESTINATION', 'R38 DYNAMEX REG TO DESTINATION'),
 ('R44 SHOULD BE CPT', 'R44 SHOULD BE CPT'),
 ('R45 VPP TO GRIMSHAW EDM TO DEST', 'R45 VPP TO GRIMSHAW EDM TO DEST'),
 ('R46 COLE FREIGHT - CALL PRIOR', 'R46 COLE FREIGHT - CALL PRIOR'),
 ('R47 CALL SUNCOR TRANS SHIP INSTRUC', 'R47 CALL SUNCOR TRANS SHIP INSTRUC'),
 ('R48 EXPRESS MAIL TO FT MCMURRAY', 'R48 EXPRESS MAIL TO FT MCMURRAY'),
 ('R49 TRANSPORTATION NOT APPLICABLE', 'R49 TRANSPORTATION NOT APPLICABLE'),
 ('R50 2 WKS PRIOR TO SHIP CALL COLE', 'R50 2 WKS PRIOR TO SHIP CALL COLE'),
 ('R51 SEE BELOW FOR INSTRUCTIONS', 'R51 SEE BELOW FOR INSTRUCTIONS'),
 ('RBA Requires RBA Approval in CCC', 'RBA Requires RBA Approval in CCC'),
 ('S46 COLE FREIGHT - CALL PRIOR', 'S46 COLE FREIGHT - CALL PRIOR'),
 ('S47 CALL SUNCOR TRANS SHIP INSTRUC', 'S47 CALL SUNCOR TRANS SHIP INSTRUC'),
 ('S48 EXPRESS MAIL TO FT MCMURRAY', 'S48 EXPRESS MAIL TO FT MCMURRAY'),
 ('S49 TRANSPORTATION NOT APPLICABLE', 'S49 TRANSPORTATION NOT APPLICABLE'),
 ('S50 2 WKS PRIOR TO SHIP CALL COLE', 'S50 2 WKS PRIOR TO SHIP CALL COLE'),
 ('S51 SEE BELOW FOR INSTRUCTIONS', 'S51 SEE BELOW FOR INSTRUCTIONS'),
 ('T08 WESTFRT TO GRIMS EDM TO DEST', 'T08 WESTFRT TO GRIMS EDM TO DEST'),
 ('T09 WESTFREIGHT TO DESTINATION', 'T09 WESTFREIGHT TO DESTINATION'),
 ('T10 MULLEN TO GRIMS EDM TO DEST', 'T10 MULLEN TO GRIMS EDM TO DEST'),
 ('T11 MULLEN TO DESTINATION', 'T11 MULLEN TO DESTINATION'),
 ('T12 PREMAY TO DESTINATION', 'T12 PREMAY TO DESTINATION'),
 ('T15 GOLOSKY TO DESTINATION', 'T15 GOLOSKY TO DESTINATION'),
 ('T34 DYN TO GRIM WHSE GRIM TO DEST', 'T34 DYN TO GRIM WHSE GRIM TO DEST'),
 ('T35 DYN TO AIR CAN AIR CAN TO DEST', 'T35 DYN TO AIR CAN AIR CAN TO DEST'),
 ('T36 DYNAMEX TO WESTJET', 'T36 DYNAMEX TO WESTJET'),
 ('T37 DYNAMEX TO DESTINATION', 'T37 DYNAMEX TO DESTINATION'),
 ('T38 DYNAMEX REG TO DESTINATION', 'T38 DYNAMEX REG TO DESTINATION'),
 ('T44 SHOULD BE CPT', 'T44 SHOULD BE CPT'),
 ('T45 VPP TO GRIMSHAW EDM TO DEST', 'T45 VPP TO GRIMSHAW EDM TO DEST'),
 ('T46 COLE FREIGHT - CALL PRIOR', 'T46 COLE FREIGHT - CALL PRIOR'),
 ('T47 CALL SUNCOR TRANS SHIP INSTRUC', 'T47 CALL SUNCOR TRANS SHIP INSTRUC'),
 ('T48 EXPRESS MAIL TO FT MCMURRAY', 'T48 EXPRESS MAIL TO FT MCMURRAY'),
 ('T49 TRANSPORTATION NOT APPLICABLE', 'T49 TRANSPORTATION NOT APPLICABLE'),
 ('T50 2 WKS PRIOR TO SHIP CALL COLE', 'T50 2 WKS PRIOR TO SHIP CALL COLE'),
 ('T51 SEE BELOW FOR INSTRUCTIONS', 'T51 SEE BELOW FOR INSTRUCTIONS'),
 ('TPP 3rd Party Prepaid', 'TPP 3rd Party Prepaid'),
 ('U01 SERV U TO DESTINATION', 'U01 SERV U TO DESTINATION'),
 ('U02 CADFRTWAY TO RYDER EDM TO DEST', 'U02 CADFRTWAY TO RYDER EDM TO DEST'),
 ('U03 GRIMSHAW TO DESTINATION', 'U03 GRIMSHAW TO DESTINATION'),
 ('U05 D&R TO GRIMSHAW EDM TO DEST', 'U05 D&R TO GRIMSHAW EDM TO DEST'),
 ('U06 D&R TO DESTINATION', 'U06 D&R TO DESTINATION'),
 ('U14 HWY9 TO GRIM EDM TO DESTINATIO', 'U14 HWY9 TO GRIM EDM TO DESTINATIO'),
 ('U17 MEL MARTIN TO GRIM EDM TO DEST', 'U17 MEL MARTIN TO GRIM EDM TO DEST'),
 ('U18 UPS TO EDM HOLD GRIM TO DEST', 'U18 UPS TO EDM HOLD GRIM TO DEST'),
 ('U19 UPS TO EDM HOLD GRIM TO DEST', 'U19 UPS TO EDM HOLD GRIM TO DEST'),
 ('U20 UPS TO EDM HOLD GRIM TO DEST', 'U20 UPS TO EDM HOLD GRIM TO DEST'),
 ('U21 UPS GOLD EDM DYN AIR CAN FMCM', 'U21 UPS GOLD EDM DYN AIR CAN FMCM'),
 ('U22 UPS GOLD TO DESTINATION', 'U22 UPS GOLD TO DESTINATION'),
 ('U23 UPS AM TO DESTINATION', 'U23 UPS AM TO DESTINATION'),
 ('U24 UPS TO EDM HOLD GRIM TO DEST', 'U24 UPS TO EDM HOLD GRIM TO DEST'),
 ('U25 AIR CAN GUARANTEED TO DEST', 'U25 AIR CAN GUARANTEED TO DEST'),
 ('U27 AIR CAN REG TO EDM GRIM DEST', 'U27 AIR CAN REG TO EDM GRIM DEST'),
 ('U28 AIR CAN REG TO DESTINATION', 'U28 AIR CAN REG TO DESTINATION'),
 ('U29 WESTJET GUARANTEED TO DEST', 'U29 WESTJET GUARANTEED TO DEST'),
 ('U31 WESTJET REG EDM GRIM TO DEST', 'U31 WESTJET REG EDM GRIM TO DEST'),
 ('U32 WESTJET REG TO DESTINATION', 'U32 WESTJET REG TO DESTINATION'),
 ('U34 DYN TO GRIM WHSE GRIM TO DEST', 'U34 DYN TO GRIM WHSE GRIM TO DEST'),
 ('U35 DYN TO AIR CAN AIR CAN TO DEST', 'U35 DYN TO AIR CAN AIR CAN TO DEST'),
 ('U36 DYNAMEX TO WESTJET', 'U36 DYNAMEX TO WESTJET'),
 ('U37 DYNAMEX TO DESTINATION', 'U37 DYNAMEX TO DESTINATION'),
 ('U38 DYNAMEX REG TO DESTINATION', 'U38 DYNAMEX REG TO DESTINATION'),
 ('U44 SHOULD BE CPT', 'U44 SHOULD BE CPT'),
 ('U45 VPP TO GRIMSHAW EDM TO DEST', 'U45 VPP TO GRIMSHAW EDM TO DEST'),
 ('U46 COLE FREIGHT - CALL PRIOR', 'U46 COLE FREIGHT - CALL PRIOR'),
 ('U47 CALL SUNCOR TRANS SHIP INSTRUC', 'U47 CALL SUNCOR TRANS SHIP INSTRUC'),
 ('U48 EXPRESS MAIL TO FT MCMURRAY', 'U48 EXPRESS MAIL TO FT MCMURRAY'),
 ('U49 TRANSPORTATION NOT APPLICABLE', 'U49 TRANSPORTATION NOT APPLICABLE'),
 ('U50 2 WKS PRIOR TO SHIP CALL COLE', 'U50 2 WKS PRIOR TO SHIP CALL COLE'),
 ('U51 SEE BELOW FOR INSTRUCTIONS', 'U51 SEE BELOW FOR INSTRUCTIONS'),
 ('UN Not Free', 'UN Not Free'),
 ('Z01 Origin', 'Z01 Origin'),
 ('Z02 Origin & Freight', 'Z02 Origin & Freight'),
 ('Z03 Origin - Insurance & Freight', 'Z03 Origin - Insurance & Freight'),
 ('Z04 Origin & Prepaid', 'Z04 Origin & Prepaid'),
 ('Z05 Destination & Freight', 'Z05 Destination & Freight'),
 ('Z06 Destination & Prepaid', 'Z06 Destination & Prepaid'),
 ('Z07 Destination', 'Z07 Destination'),
 ('ZCA PCA title - Tax at Destination', 'ZCA PCA title - Tax at Destination'),
 ('ZCR Associate Delivered', 'ZCR Associate Delivered'),
 ('ZTX FCA-Tax at Destination', 'ZTX FCA-Tax at Destination')]



plant_location_list = [(None, "Select plant location (will restrict procurement to the assigned plant only)"),
('764 Fort Hills', '764 Fort Hills'),
 ('402 Lubricant Centre', '402 Lubricant Centre'),
 ('EDMW Edmonton Lubricants Centre', 'EDMW Edmonton Lubricants Centre'),
 ('WPGW Winnipeg Lubricants Centre', 'WPGW Winnipeg Lubricants Centre'),
 ('1000 OS Site Wide Services', '1000 OS Site Wide Services'),
 ('1060 OS Energy & Utilities', '1060 OS Energy & Utilities'),
 ('1100 OS Mining', '1100 OS Mining'),
 ('1200 OS Extraction', '1200 OS Extraction'),
 ('1210 OS Reclaimation', '1210 OS Reclaimation'),
 ('1300 OS Upgrading', '1300 OS Upgrading'),
 ('1310 ETF - Hot Bitumen Terminal', '1310 ETF - Hot Bitumen Terminal'),
 ('1400 OS Firebag', '1400 OS Firebag'),
 ('1500 Millenium Project (SStone)', '1500 Millenium Project (SStone)'),
 ('1600 Firebag Project (SStone)', '1600 Firebag Project (SStone)'),
 ('1800 Gibson Terminal', '1800 Gibson Terminal'),
 ('1810 Oil Sands Pipeline', '1810 Oil Sands Pipeline'),
 ('1900 OS Logistics Plant', '1900 OS Logistics Plant'),
 ('1930 Forming Plant (Oil Sands)', '1930 Forming Plant (Oil Sands)'),
 ('1931 Terminal BC (Oil Sands)', '1931 Terminal BC (Oil Sands)'),
 ('754 OS MacKay River', '754 OS MacKay River'),
 ('8063 OSCL Steepbank - Gas', '8063 OSCL Steepbank - Gas'),
 ('8064 OSCL Steepbank - Diesel', '8064 OSCL Steepbank - Diesel'),
 ('8065 OSCL Main Admin. Fuel Area', '8065 OSCL Main Admin. Fuel Area'),
 ('1030 Pipeline', '1030 Pipeline'),
 ('0AA Newfoundland Rack Forward', '0AA Newfoundland Rack Forward'),
 ('0AB Prince Edward Island RF', '0AB Prince Edward Island RF'),
 ('1AA New Brunswick Rack Forward', '1AA New Brunswick Rack Forward'),
 ('2AA Nova Scotia Rack Forward', '2AA Nova Scotia Rack Forward'),
 ('302 Raffinerie/Dépot de Montréal', '302 Raffinerie/Dépot de Montréal'),
 ('304 Suncor Montreal Sulphur Plant', '304 Suncor Montreal Sulphur Plant'),
 ('3AA Rack Forward - Quebec', '3AA Rack Forward - Quebec'),
 ('4000 Sarnia Refinery', '4000 Sarnia Refinery'),
 ('4015 MDI Terminal', '4015 MDI Terminal'),
 ('4020 London Terminal', '4020 London Terminal'),
 ('404 Oakville Terminal', '404 Oakville Terminal'),
 ('422 Ottawa Product Terminal', '422 Ottawa Product Terminal'),
 ('4AA Ontario Rack Forward', '4AA Ontario Rack Forward'),
 ('5AA Manitoba Rack Forward', '5AA Manitoba Rack Forward'),
 ('6AA Saskatchewan Rack Forward', '6AA Saskatchewan Rack Forward'),
 ('702 Edmonton Refinery/Terminal', '702 Edmonton Refinery/Terminal'),
 ('7AA Alberta Rack Forward', '7AA Alberta Rack Forward'),
 ('7AB NWT Rack Forward', '7AB NWT Rack Forward'),
 ('802 Burrard Products Terminal', '802 Burrard Products Terminal'),
 ('8AA British Columbia Rack Forward', '8AA British Columbia Rack Forward'),
 ('8AB Yukon Rack Forward', '8AB Yukon Rack Forward'),
 ('991 Sheridan Park Business Centre', '991 Sheridan Park Business Centre'),
 ('994 Oakville Business Centre', '994 Oakville Business Centre'),
 ('STMN National Site Maintenance', 'STMN National Site Maintenance'),
 ('5000 Suncor Energy Services Inc.', '5000 Suncor Energy Services Inc.'),
 ('5010 Corporate (Fort McMurray)', '5010 Corporate (Fort McMurray)'),
 ('5020 Corporate (Firebag)', '5020 Corporate (Firebag)'),
 ('5030 Corporate (Edmonton)', '5030 Corporate (Edmonton)'),
 ('5040 Corporate (Mississauga)', '5040 Corporate (Mississauga)'),
 ('5050 Corporate (Sarnia)', '5050 Corporate (Sarnia)'),
 ('5060 Corporation (Québec)', '5060 Corporation (Québec)'),
 ('5070 Corporate (Newfoundland)', '5070 Corporate (Newfoundland)'),
 ('7000 Denver Refinery', '7000 Denver Refinery'),
 ('7030 SUSA Terminals', '7030 SUSA Terminals'),
 ('7050 Refinery Business Center - Sun',
  '7050 Refinery Business Center - Sun'),
 ('7600 Denver Pipeline', '7600 Denver Pipeline')]
