from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home_page, name='csa_app_home'),
    path('redirect-form1/', views.form_1, name='csa_app_form_1'),
    path('redirect-form1-parent-only/', views.form1_parent_only, name='csa_app_form_1_parent_only'),
    path('redirect-form1-parent-and-children/', views.form1_parent_and_children, name='csa_app_form_1_parent_and_children'),
    path('redirect-form1-add-children/', views.form1_add_children, name='csa_app_form_1_add_children'),
    path('redirect-home_page/', views.home_page, name='csa_app_redirect_home_page'),
    path('redirect-dummy_page/', views.dummy_page, name='csa_app_redirect_dummy_page'),
    path('redirect-form2-first-release_NDA/', views.form2_first_release_NDA, name='csa_app_redirect_form2_first_release'),
    path('redirect-form1-first-create_NDA/',views.form1_parent_only, name='csa_app_redirect_form2_first_create_NDA'),
    path('redirect-form2-amendment/', views.form2_amendment, name='csa_app_redirect_form2_amendment'),
    path('redirect-dummy_page2_first_release_NDA/', views.dummy_page2_first_release_NDA, name='csa_app_redirect_dummy_page2_first_release'),
    path('redirect-dummy_page2_amendment_date/', views.dummy_page2_amendment_date, name='csa_app_redirect_dummy_page2_amendment_date'),
    path('redirect-dummy_page2_amendment_header/', views.dummy_page2_amendment_header, name='csa_app_redirect_dummy_page2_amendment_header'),
    path('redirect-dummy_page2_amendment_date_plus_header/', views.dummy_page2_amendment_date_plus_header, name='csa_app_redirect_dummy_page2_amendment_date_plus_header'),
    path('redirect-form2_first_release_option_selector/', views.form2_first_release_option_selector, name='csa_app_redirect_form2_first_release_option_selector'),
    path('redirect-form2-first-release-parent-only/', views.form2_first_release_parent_only, name='csa_app_redirect_form2_first_release_parent_only'),
    path('redirect-form5/', views.form5, name='csa_app_redirect_form5'),
    path('redirect-dummy_page2_forms2_5/',views.dummy_page2_forms2_5, name='csa_app_redirect_forms2_5'),
    path('redirect-form2-first-release-parent-and-children/',views.form2_first_release_parent_and_children,name='csa_app_redirect_forms2_first_release_parent_and_children'),
    path('redirect-form2-first-release-add-children/',views.form2_first_release_add_children,name='csa_app_redirect_forms2_first_release_add_children'),
    path('redirect-form2_amendment_selector/',views.form2_amendment_selector,name='csa_app_redirect_form2_amendment_selector'),
    path('redirect-form2_nonNDA_amendment_target_value_selector/',views.form2_nonNDA_amendment_target_value_selector,name='csa_app_redirect_form2_amendment_target_value_selector'),
    path('redirect-form2_nonNDA_amendment_target_value_opt1/',views.form2_nonNDA_amendment_target_value_opt1,name='csa_app_redirect_form2_nonNDA_amendment_target_value_opt1'),
    path('redirect-form2_nonNDA_amendment_target_value_opt2/',views.form2_nonNDA_amendment_target_value_opt2,name='csa_app_redirect_form2_nonNDA_amendment_target_value_opt2'),
    path('redirect-form2_nonNDA_amendment_items_update/',views.form2_nonNDA_amendment_items_update,name='csa_app_redirect_form2_nonNDA_amendment_items_update'),
    path('redirect-coming-soon/',views.coming_soon,name='csa_app_coming_soon'),
    path('redirect-dummy_page2_form2_amendments/',views.dummy_page2_form2_amendments,name='csa_app_redirect_form2_dummy_page2_amendments'),
    path('redirect-form2_nonNDA_amendment_date_extension/',views.form2_nonNDA_amendment_date_extension_selector,name='cas_app_redirect_form2_nonNDA_amendment_date_extension_selector'),
    path('redirect-form2_nonNDA_amendment_date_extension_opt1/',views.form2_nonNDA_amendment_date_extension_opt1,name='csa_app_redirect_form2_nonNDA_amendment_date_extension_opt1'),
    path('redirect-form2_nonNDA_amendment_date_extension_opt2/',views.form2_nonNDA_amendment_date_extension_opt2,name='csa_app_redirect_form2_nonNDA_amendment_date_extension_opt2'),
    path('redirect-form2_nonNDA_amendment_header_details/',views.form2_nonNDA_amendment_header_details_selector,name='cas_app_redirect_form2_nonNDA_amendment_header_details_selector'),
    path('redirect-form2_nonNDA_amendment_header_details_opt1/',views.form2_nonNDA_amendment_header_details_opt1,name='csa_app_redirect_form2_nonNDA_amendment_header_details_opt1'),
    path('redirect-form2_nonNDA_amendment_header_details_opt2/',views.form2_nonNDA_amendment_header_details_opt2,name='csa_app_redirect_form2_nonNDA_amendment_header_details_opt2'),
    path('redirect-form2_nonNDA_amendment_payment_terms/',views.form2_nonNDA_amendment_payment_terms_selector,name='csa_app_redirect_form2_nonNDA_amendment_payment_payment_selector'),
    path('redirect-form2_nonNDA_amendment_payment_terms_opt1/',views.form2_nonNDA_amendment_payment_terms_opt1,name='csa_app_redirect_form2_nonNDA_amendment_payment_terms_opt1'),
    path('redirect-form2_nonNDA_amendment_payment_terms_opt2/',views.form2_nonNDA_amendment_payment_terms_opt2,name='csa_app_redirect_form2_nonNDA_amendment_payment_terms_opt2'),
    path('redirect-lock-unlock/',views.lock_unlock, name='csa_app_redirect_lock_unlock'),
    path('redirect-dummy_page2_lock_unlock_NDA/', views.dummy_page2_lock_unlock_NDA, name='csa_app_redirect_lock_unlock_NDA')
    #path('dummy_page/', views.dummy_page, name='csa_app_dummy'),
]
